[env]
_.path = ["{{config_root}}/node_modules/.bin"]

[tasks.check]
depends = ["format-check", "type-check", "lint", "test"]

[tasks.format]
run = "prettier --write package.json src/. tests/. tsconfig.json vitest.config.ts"

[tasks.format-check]
run = "prettier --check package.json src/. tests/. tsconfig.json vitest.config.ts"

[tasks.lint]
run = "biome lint src/. tests/. && eslint src/. tests/."

[tasks.lint-fix]
run = "biome lint src/. tests/. --fix && eslint src/. tests/. --fix"

[tasks.test]
run = "vitest --run"

[tasks.test-watch]
run = "vitest"

[tasks.type-check]
run = "tsc --noEmit"

[tools]
node = "lts"
"npm:pnpm" = "latest"
